apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: spring-boot-argo-rollout
spec:
  replicas: 3
  strategy:
#    canary:
#      steps:
#        - setWeight: 33
#        - pause: {}
#        - setWeight: 66
#        - pause: {duration: 10}
    blueGreen:
      activeService: spring-boot-argo-rollout
      autoPromotionEnabled: false
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: spring-boot-argo-rollout
  template:
    metadata:
      labels:
        app: spring-boot-argo-rollout
    spec:
      containers:
        - name: spring-boot-argo-rollout
          image: localhost:5000/spring-boot-argo-rollout:1.0
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            requests:
              memory: 32Mi
              cpu: 5m