apiVersion: v1
kind: Service
metadata:
  name: spring-boot-argo-rollout
spec:
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: spring-boot-argo-rollout